### ISSUE TITLE
Not able to run application

### ISSUE THREAD

**Issue by FernandaS** [micro-frontends-demo/browse#16]
Hi guys- I've tried to run each individual application but I was not successful. I've tried node version: 10, 12 and 14 and they all have the same issue below. Also, how does the application know to run in the "container" element? How does the public folder gets wired with the rest of the application? 

<img width="796" alt="Screen Shot 2021-03-18 at 10 10 37 AM" src="https://user-images.githubusercontent.com/8325138/111649849-be44e480-87d2-11eb-92da-338624dcf852.png">

**Comment by agsmorodin** [comment]
please double check that you have your content service up and running.   this is one of the steps from the README.md

this is where the browse service loads the react from.

**Comment by camjackson** [comment]
@agsmorodin is correct - this issue usually means you haven't started the shared content server as the README describes. Please let me know if that's not the case and I will reopen.
